### PR TITLE
Fix serialize_record module import error

### PR DESCRIPTION
**Pull request by wallacesky**

### CODE REVIEW

**Comment by Steven-Chan** [comment]
@wallacesky 

Travis did not pass 😢 

```
$ pylama chat
chat/database.py:0:0: Incorrectly sorted imports. [isort]
chat/message_handlers.py:0:0: Incorrectly sorted imports. [isort]

The command "pylama chat" exited with 1.
```

**Comment by wallacesky** [comment]
It's still applying `skygear:1.1.1` in the project.
This makes this PR fail the build

**Comment by rickmak** [comment]
refs: https://github.com/SkygearIO/py-skygear/pull/175

I think we will still want to use the new import path anyway.

**Comment by rickmak** [comment]
Merge via aa29fb7

**Pull request closed without merging**
