### PR TITLE
Add style to chat demo

### PR DESCRIPTION
**Pull request by david90**
- Added style to the demo
- The message page is not completed yet

### CODE REVIEW

**Comment by rickmak** [comment]
I will fix the rest.

**Comment by rickmak** [comment]
I tried to make it merge-able, but fail.

1. The text cannot select after apply the style.
1. May I have the origin url of the style?

**Comment by rickmak** [comment]
@david90 I am consider to close this PR if no more update or input to make it works. Since it is not critical.

**Comment by david90** [comment]
- @rickmak I just applied this style https://codepen.io/Varo/pen/gbZzgr
- No problem, you can close it. we can base on this example later anyway.

**Pull request closed without merging**
