### PR TITLE
Remove is direct message

### PR DESCRIPTION
**Pull request by kaojohnny**
connects #40
- not sure if it's okay to remove `getOrCreateDirectConversation` API of js-SDK.

### CODE REVIEW

**Comment by oursky-travis** [comment]
@kaojohnny, thanks for your PR! By analyzing the annotation information on this pull request, we identified @lampercy, @rickmak and @chankiyu22 to be potential reviewers

**Comment by rickmak** [comment]
@kaojohnny I think the `getOrCreateDirectConversation` is good helper function for user?

Or most likely the user will need to do it himself. We can reference on how other developer use it: https://github.com/skygear-demo/ionic-chat-demo/blob/1fa9bccd173b4434bab5669bd2297e16eade3698/www/js/services/conversations.js#L143

So keep it and add `transientInclude` and return the the same object as in `getConversation` should be a better solution.

**Comment by kaojohnny** [comment]
@rickmak The main purpose of `getOrCreateDirectConversation` function is to make sure the uniqueness of a one-to-one direct conversation. My consideration is that this behavior is more like a business logic, so shouldn't be handled by the client. 

1. I don't think we should keep the idea `Direct message` or `Direct conversation` idea after we remove `is_direct_message` attribute. 
2. We don't provide `getOrCreateConversation`, so the same group of users can create multiple conversations without limitation. No reason to provide a function for the direct conversation on the contrary.
3. We don't provide a `before-save` function to check the uniqueness when admin tries to remove participants down to one participant only (direct conversation).

**Comment by rickmak** [comment]
We are providing business logic in this plugin. Intended for user to checkout
and use it. All user need is to code the UI.

> We don't provide a before-save function to check the uniqueness when admin
> tries to remove participants down to one participant only (direct
> conversation).

This is very valid from engineering point of view. But maintain uniqueness of
one-to-one conversation is not the business requirement here. The requirement
here is a fast way for user A to query back and display the converation with
user B. Or create one. You may take reference to facebook.

You can create a converation on Facebook with multiple people, and people can
leave. There can be a moment that the group have only 2 person. But it is
okay, and it won't confuse user. Because a group will have history indicate a
user left. And the user is fully awear that is a group. Not a one-to-one
conversation.

Even, a group can have only 1 participants. Which does not logical if you just
look at the converation table without considering the history and how is it
created.

Re: `getOrCreateConveration`, restricting same group of users to create
multiple conversations is counter user intuitive.

Having the above consideration. Seem the `is_direct_message` worth it place at
the schema? Sorry cannot come up with above consideration at the very
beginning.

**Comment by kaojohnny** [comment]
Thanks, no problem, let's keep current implementation.

**Comment by chpapa** [comment]
Sorry for jumping in late, but I think the business requirements can be clarified with it.

Actually I think there are two ways usually how chat room was handled:
1. Distinct by chat room; thus similar with what Rick said, it doesn't matter if the chat room would changed to two participants.

2. Distinct by participants; similar to how slack handle chat room. If two chat room have the same set of participants, they merge. So if it is two users, it is identical to the DM chat room.

I am not sure if we really need DM? But I think it would be good if we can add a boolean properties to conversations say distinctByParticipants (similar to layer.com), and the server will merge chat room if the attr is true with same set of users.

That should model different business requirements well

**Comment by rickmak** [comment]
We will re-model it at #47

**Pull request closed without merging**
